apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::302743383270:role/eksctl-k8sb29-cluster-01-nodegroup-NodeInstanceRole-Gp9OrbfQnJgm
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::302743383270:role/K8SB32-MGMT-Role
      username: admin_role_office
      groups:
      - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::302743383270:user/eksadmin
      username: eksadmin
      groups:
      - system:masters
kind: ConfigMap
